### ISSUE TITLE
Interpretation des INT dans le switch de l'interpretation du code FEN

### ISSUE THREAD

**Issue by Borobo** [TeamTop1/Avalam-Diag-2.0#3]
https://github.com/TeamTop1/Avalam-Diag-2.0/blob/97cf09c2b723aa139532732ce5299b500a74fcab/Avalam/libavalam-final/example/maindiag.c#L87
Il faut trouver une solution pour que les int soit bien interprétés tout en gardant la structure du switch.

**Comment by ClementBrd** [comment]
mais oui
