### ISSUE TITLE
IL MANQUE UN I++

### ISSUE THREAD

**Issue by ClementBrd** [TeamTop1/Avalam-Diag-2.0#4]
https://github.com/TeamTop1/Avalam-Diag-2.0/blob/97cf09c2b723aa139532732ce5299b500a74fcab/Avalam/libavalam-final/example/maindiag.c#L91

**Comment by Borobo** [comment]
Bonjour,

Merci pour votre observation, nos services de programmation seront mis a disposition pour regler ce problème veuillez nous excuser pour cette gène occasionée.

Bonne Enculade,
Cordialement, M.Lesueur
